### PR TITLE
Update url for exercism repo

### PR DESCRIPTION
**Pull request by PatrickMcSweeny**

### CODE REVIEW

**Comment by rpottsoh** [comment]
I would just like to point out that the old url and the new url end up at the same place.  Is it necessary to make this change?  Will the old url eventually stop working in the manner it is right now?  Is there an issue that relates to this PR?

**Comment by NobbZ** [comment]
@rpottsoh the current redirects will stop working forever as soon as someone accidentally creates an exercism.io repo under exercism org.

Or as soon as GitHub decides to not do these redirects anymore.

Apart of that, I consider this as a good practice to change URLs in local documents to adhere to a name change.

**Comment by iHiD** [comment]
@rpottsoh said: 
> Is there an issue that relates to this PR?

@kytrinyx Maybe another one to grep and script for when you get an hour?

**Comment by iHiD** [comment]
PatrickMcSweeny Thanks! :)

**Pull request merged**
